version: '3'
services:
  ghostblog:
    image: 
      ghost:1-alpine
    ports:
      - "2368:2368"
    depends_on:
      - "database"
  database:
    image:
      mysql:5.7
    enviroment:
      MYSQL_ROOT_PASSWORD: root
